name: movie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Responsive Design
  flutter_screenutil: ^5.9.3
  
  # Shared preferences for local storage
  shared_preferences: ^2.3.3
  
  # State management
  flutter_bloc: ^8.1.6

  # Code generator
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Networking
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.8.0
  retrofit_generator: ^10.0.6

  # Dependency Injection
  get_it: ^8.2.0

  # Shimmer for loading states
  shimmer: ^3.0.0

  # For caching network images
  cached_network_image: ^3.4.1

  # Local database for caching
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.4
  path: ^1.9.1

  # Connectivity checking
  connectivity_plus: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code generator
  build_runner: ^2.10.1
  json_serializable: ^6.11.1
  drift_dev: ^2.20.0

flutter:
  uses-material-design: true
